### ISSUE TITLE
Hodnocení úkolu #1

### ISSUE THREAD

**Issue by tommander** [JitkaHo/mujprojektik#1]
<p>Moc hezky udělaný web, designově velice pěkně sladěný, menu hezky funguje, při zobrazení na mobilu se vše přizpůsobí. Dobrá práce 👍 </p>
<p>Přesto si směle dovolím pár poznámek:</p>
<ol>
  <li><kbd>index.html</kbd> např. řádky 43&ndash;47, 53&ndash;103, 111&ndash;124, 144 &mdash; trošku bych zharmonizoval odsazování; třeba pod některými nadpisy (h1, h2, ...) jsou prvky odsazeny, někde ne, na některých místech zas ukončovací značka <code>&lt;/neco&gt;</code> nesedí s odsazením počáteční značky <code>&lt;neco&gt;</code>.</li>
  <li><kbd>index.html</kbd> řádek 51 &mdash; obecně nedoporučuji používat diakritiku v názvech tříd/id, ale mezery jsou bohužel vysloveně špatně, protože CSS pak nepochopí, že to druhé slovo ještě patří k třídě a bude to interpretovat úplně jinak. Ty to sice pak ve <kbd>style.css</kbd> nepoužíváš, ale kdybys to potřebovala, nepodaří se ti na tu třídu/id odkázat.</li>
</ol>
<p>Tyhle drobnosti bych poprosil opravit a pak to bude úplně paráda :) Když s některým bodem nebudeš souhlasit nebo k němu budeš potřebovat dodatečné info, určitě se ozvi :) Děkuji.</p>

**Comment by JitkaHo** [comment]
Děkuju za hodnocení a postřehy.
Snažila jsem se kód uspořádat, evidentně si s tím ani prettier neporadil :)

A opravila jsem i bod 2 - to jsem si vůbec neuvědomila, díky.

Jitka

**Comment by tommander** [comment]
Super, za mě fajn, dobrá práce :) 👍
